100
....X...........X....X..X...X.X..X.........X.X..X.X.....X.X..................X...X....XX........X.X.
X..X..........X..X....X.........XX.X.XX...XX..X...X..X.......XX...X..........X...X.....X....X.X.....
..........X....X......X..X...X..........X..X......X....X...X.X..X..X.....X......X...........X......X
......X.X........X..X...........X..XX...X..........X........XX...X....X..XX..X..X......XX...XX......
....X....X..X...XX.X...X...X.................X....XX..XX...X....X.X.....X........X.............X....
X.X......X...X..X.X.X.......X...X..X............XXX....X....X..X.XX..X...XX....XXX.....X.......X....
...X.X....X...X......X.X..X.....X.....X.XX..............X.........X.X.......X..XX.........XX........
..X..XX.......X..X........X.........XX...........X.XX...........X.........X.....XX.X..........XX.X..
...X..........X.....X....X.XX....X..XX.X.X..........X.......XX...X......X.X.....X...X.....X.........
.X...................XX........X..X..........X.X...X.......X..X.X....X.........X...X.X..X.......X...
X....X....X..X.......X......X..X.X..X.........X.....XXXXX..................X....................X...
X.XX......X............X.X....X....X.X.........XXX....XX.....XXXXX...XX.XX...X.XX.....X.X......X.X..
..X..X..XXX.X.........X.....XX...X....X..................X..X..............X..X.XX....XX.X..........
..............X.....X.X...X.X.X..........X...X.X...X...X...X.....X..X...X.X......X.....X...X..X....X
.....................X...............X.X........X..XX.........X.X.......X....X......XXX.....X.X.....
.XX......X..X.........XXX.....X.........X..X.......XX.........X.X..X..X..X...X....XX.....XX.X...X...
......X........X.XX......X..............X....XX.......XX...................X........X.....X.......XX
.XXX......XX................XX...X......X..XX......XXXX......X...X...............X.X................
...X............XX....X....X...XX......X....X...X........X...X...X......X.....X.............X.......
..............XXX.XX..........X..........XXX...X...........X....XX.........X..X......X........X.X...
.....X.........X.X.......X.X......X.............X..XX......X.......X.........X.....XXX....X......X..
....XX..........X....X.XX..X..X...X.............X.........X........XX..X..XX................X..XXX..
.......XX....X..X.....X.XX..X.X.X.X..XX..X.X...X.X.X.....X..X.X.XX..XX.....X....X...X.....XX.X......
...X......X.X..X...XX.X.X..X.X.......X.....X.X......X.....X..XX...X...X..XX..X.X.........X.X.......X
.......X..........X...X......X.........X...X....X..X....X..X.......X..XX......X..X.XX......XX.......
................X.....X.........X...X...............X....X...X.XX....X....X..X.XX.....X....X....X...
X..X.............X.....X....X...............X..XX..X............X...................X........X.X....
..X..........X...................XX.X.X...................X...........X....X....X.....X.X...X.XX.X..
.....XX....X......X.....X.X.................X...XXX..X.X.XX.....X.........X...........X........X....
....X....X.XXX.....X...........X................................X.X.....................X....X......
..X..X.X..............X.......X........X........X..............X....X....X.............X............
XX...X..X.X...X....X................X...........XXX...........X.XXX..X....XX...X.......X.....X.X....
.X...............X.XXX......XX.....X.......X...X............X.XX....................X..XXX..........
.......XX......X.........X..X........X....X.X.....X.X...X.X.....X............X.X....................
XX.XX.........XX....X.....X.....XXX..X........X...X.XX...X.X..X...X......X....X..X..XX...X.....XXXX.
..X..XXX....X.XX.XX....X.....XX......X.............X.X.X...XX.X.XX..X...XX..XX.....X..X......X.X..X.
X.....X.....X......X........X..X...X.X.....X...........X..X....X...X..X......X.XX..X..X.X.....X.....
.........X...X....X......X.....X...X.........X.....XXXX.......X.X.......X...X..X.XX...X..X......X.X.
............X.....X..X....X....XX...X.....X.........X.X..X............X..X.....X...X..............X.
.....X.X..X......X........X..........X......X......X.............X.X..X.....X.X...........X........X
...X..............XX..X.........X............XXX..........X..........X...X..X.X.........X....XX...X.
...................X......X....XX.......XX.....X....XX.X........X.....X..X.....X.X.XXX.....X........
....X.X........XXX......X...X.X.....X.X............X.....X......X.X.XX......X.....X...XXX.........XX
.X...XX...X.........................X......X....X.........XX........X....XX..X..XX.XX.......X...X.X.
......X..X.X.................X..X.....X.X.....X....XX..X.X.XX....X.....X..X.X..X....X......X......X.
...XXX........X........X.XX..X.........X.....X..X...............X........................XX..X......
........X....X...X.....X......X.........................XX......XXX.X........X.X....X.X............X
...X.X..X...X.......XXXX.......X.......X..XX.X...X......XX..X...X.XX..X......X......X..X.X..X.......
X....X.......XXX.X..X.XX.XX...X.X.......XX.X..XX..........X.XX.X.X......X............X..X...X..XXX..
XXX...............X...X....XXX.X...X.....X.....X.......XX..X....X.....X....X........................
X....X......X....X...X..........X..........X..........XXX.........X...X....................X......X.
...XX.......XX...XXXX..X.......X.X.......X.X.......X.X.......X...........XX......X........XX..X..X..
X.X........XX.X.....X......X.X..X.......X...............X...XXXX...........X....X.....X......X......
..X.....X........X..X....X.........XX.XXXX...X....X.X.....................X......X......XX.X...X.X..
...X..XXX............X.....XX....................X..X..XXX....X...............X.....XX.............X
XXXX....X...X...XX...X.............X.....X.....X..........XX..X................X.............X.X.X.X
....X...................X...X......X......X......X..X..............X.......X........X..X.X......X...
.....X.X.X.X........X...X...XX...XX.....XX........X.X..X..X....X.........X.X.......X..X...........X.
X.......X.....X.........X.............X...X...........XX...X.X.XX.......X............X.........X.X..
.....X..X.X..........XX.X......X....X.X.XXX......XX.....X.X...........X......X..........X.XXX.XX.X..
................XX.....X..XX................XX..X....X............X..X..XX....X....X.......X....X..X
.X.......X............X.X....................X........X..........X..............X........X..........
........X.....X....X.X...X.X.....X.......X.X...X.....X.X..X.X.......X...X.....X........XX....X..X..X
X....XX.X.X........XX.X...X......X...X.X....X...X....X...XX.X..........................X..X.X.X...X.
..X...X.......................X......XX.......X..XX....X..X.X....X............X........X..XX....XX..
.....X...X.................XX......X.......X....XXX......X.......X.........X...X.....X.X...X...X....
....X....X..XXX..XX........XX..X.....X.X............X............X..................XX..........X...
XX.....X...X.X....X....X..X...X....XX.....X.....X..X...X.X......X...........X...XX.X.....X..........
.........X...X...X.X......X...........X.....X...XX.X....X.........X....X.....X..X.....X.....X..X....
........XX..X......X..............X...X..........................................X...X.......XX.....
.X.......X.....X..XX...XX........................X...X.............XX.....X...X................X....
...X.......X.XX..X.X....X.......X..X...X.......X..X.X.....XX..X.XX.....X.......X.....X.....X...X...X
...........X...X.X...X.X........X....X..X...X........XX.X...XX..X...X...X......X..XX.........X..X...
...X.X....X.XX.X.....X........X.X.........X.......XX.......XX..X...XX.X....X......X...X...X.XXX.....
......X.........X..X..X...X.......X...XXX....XXX........XX..........XX...X...................X....X.
.X.X........XXXX.X....XX........X...........X......X......X.X...X.X....XX......X..X....X........X...
...XXX...........X..X.....X.X........X..............X..........XX...X.X..X.X............X.......X...
X.................X.XX..X......X.XXX........X.X...X....X.X...X.XXX..X............XX.......X...X..X..
......X..XXXXXX..........XX..X...XX.....XXX.....X......X....X.X..X.X.....XXX.....X.XX...............
...X........X...X.X.X................XX....X.X...X..........X......X..X...XX.X.XXX.X...X.......X....
.....XX..X...X......X................X..........X....X.......X.X.....X..X..X..XX..XX.X...........X.X
.X.........X....X....X.....X...X..X......X..X..X.....X.........XXX.................X.X......XX......
...XX.X.X..X..X..X...X...XX............X..X..X....X......X..X...X.....X.............X...X......X....
X.........XX.XX..X.....XX..X....X............X.........X.........X.X..X.....X............X.......X..
..XX.XX........X.X.............X..........X....X.X..X.XXX.X....X.X............X.X.X....X...X........
.X........X....XX..XX......X...X..X.........XXX.XX......X.XX...X...X.XX.........X.............X.....
.X............X...X....X...X........X.................X.......X.X......X..X..X..................XXX.
.X.X..X.X...........X.X.......XXX...X...........X.X.....X..X.X..X......X.X..............XX.....X...X
.........X.X...X.......X.........X........X........XX....X...X.X.XXX.......X.............X..X.X.....
.....................X...XX.X..X....X.........X......X.X..X...XX....X..........XX....X...XX.......X.
.................XX...X......XX.X....X...X...........XX....X.X...X...XXX....X.X.X.X.X....XXX......X.
..X.....X...X.....X.........X.....X.X.X.........X.....X.....X..............X.....X............XX.X..
...............X....XX...............XX......X.........XX.............X.X.........X........X.X...X..
X...XX.....X..........X.......X......XX....X......X.....X........X..X.X.......XX....................
...X..X..XX.........X.X.....X.X.....X....X....X..X..X..............X.X.........X.X..XX.X.........X..
.............X..XX..X.X...................................XX............XX..X..X.X..X.XX......X.....
XX...X...X.X...X......X.....X.X...X.......X.X.X...XX......X..X...XX......X.....X....X............X.X
............X................XX..XX..X..XX............................X...X..X........X....X.....XXX
.......X..X.......X............X...X.....X............X....X..X...........X...X.........X...........
X..X..X...X.......X....X.X.....XX............X.........X....XX.....X.X..X......X.X...X.X.X.X...X.XX.
27 96 94 33

expected answer: 16


************************************************************************************************8
************************************************************************************************8
************************************************************************************************8
************************************************************************************************8

88
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
.......................................................................................X
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X
X....................................................................................X.X
X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X.X
X.X................................................................................X.X.X
X.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X.X.X
X.X.X............................................................................X.X.X.X
X.X.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X.X.X.X
X.X.X.X........................................................................X.X.X.X.X
X.X.X.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X.X.X.X.X
X.X.X.X.X....................................................................X.X.X.X.X.X
X.X.X.X.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X.X.X.X.X.X
X.X.X.X.X.X................................................................X.X.X.X.X.X.X
X.X.X.X.X.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X.X.X.X.X.X.X
X.X.X.X.X.X.X............................................................X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X........................................................X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X....................................................X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X................................................X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X............................................X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X........................................X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.X....................................X.X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X.X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.X.X................................X.X.X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.X.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.X.X.X............................X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XXXXXXXXXXXXXXXXXXXXXXXXXX.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X........................X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XXXXXXXXXXXXXXXXXXXXXX.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X....................X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XXXXXXXXXXXXXXXXXX.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X................X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XXXXXXXXXXXXXX.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X............X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XXXXXXXXXX.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X..........X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X..........X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X..........X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X..........X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X..........X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X..........X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X..........X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X..........X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XXXXXXXXXXXX.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X..............X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XXXXXXXXXXXXXXXX.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X..................X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XXXXXXXXXXXXXXXXXXXX.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X......................X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XXXXXXXXXXXXXXXXXXXXXXXX.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X..........................X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.X.X.X..............................X.X.X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.X.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X.X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.X.X..................................X.X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.X......................................X.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.X..........................................X.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.X..............................................X.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.X..................................................X.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.X......................................................X.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.X..........................................................X.X.X.X.X.X.X.X
X.X.X.X.X.X.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X.X.X.X.X.X.X
X.X.X.X.X.X.X..............................................................X.X.X.X.X.X.X
X.X.X.X.X.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X.X.X.X.X.X
X.X.X.X.X.X..................................................................X.X.X.X.X.X
X.X.X.X.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X.X.X.X.X
X.X.X.X.X......................................................................X.X.X.X.X
X.X.X.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X.X.X.X
X.X.X.X..........................................................................X.X.X.X
X.X.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X.X.X
X.X.X..............................................................................X.X.X
X.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X.X
X.X..................................................................................X.X
X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X
X......................................................................................X
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
1 0 44 44

expected output: 79
